### ISSUE TITLE
RN 0.6.x 'WCLShineButton/WCLShineButton-Swift.h' file not found

### ISSUE THREAD

**Issue by shadowed87** [prscX/react-native-shine-button#25]
Every time I try to build I get

'WCLShineButton/WCLShineButton-Swift.h' file not found
on React 0.6.x

Am I the only one having this problem?
How can I fix this?

**Comment by Bunhouth99** [comment]
@shadowed87  did you found any solution, yet?

**Comment by prscX** [comment]
I have added support for RN61+. Using RN61+ you won't face the raised issue. Could you please upgrade to latest RN and try.

Please follow installation steps as per README.

Thanks
</ Pranav >

**Comment by Bunhouth99** [comment]
> I have added support for RN61+. Using RN61+ you won't face the raised issue. Could you please upgrade to latest RN and try.
> 
> Please follow installation steps as per README.
> 
> Thanks
> </ Pranav >

thanks everything work fine since RN 0.61+ include `Better CocoaPods support `.

**Comment by Bunhouth99** [comment]
@prscX  it would be great if library can support static asset or image from RN.
Ex.
`<RNShineButton shape={'resource-image'} color={"#808080"} fillColor={"#ff0000"} size={100} />`
or
`<RNShineButton shape={require('image.png')} color={"#808080"} fillColor={"#ff0000"} size={100} />`

**Comment by prscX** [comment]
Can be easily done, I will enable the requested feature.

**Comment by prscX** [comment]
@Bunhouth99:  I have enabled and pushed release which supports static asset images.  You need to place your images in platform asset in order to render.

I have copied this source from other projects where it was supported, I have not personally tested but it should work. Let me know incase it does not work.

Please refer README for adding static images.

Thanks
</ Pranav >
